# SPDX-FileCopyrightText: 2024 The Forkbomb Company
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: 📢 Tests, Release & Publish
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.head_ref ||  github.ref }}
  cancel-in-progress: true

jobs:
  packageManager:
    name: 🔍 Get pnpm version to use
    runs-on:  ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        architecture:
          - x64
          - arm64
          - armv7
        exclude:
          - os: windows-latest
            architecture: armv7
          - os: windows-latest
            architecture: arm64
    outputs:
      version: ${{ steps.ver.outputs.version }}
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
      - name: 🔍 Get pnpm version from pacakgeManager field
        id: ver
        run: |
          echo "version=$( jq -r '.packageManager' package.json | cut -d@ -f2 )" >> $GITHUB_OUTPUT

  test:
    name: 🧪 Pnpm test
    needs: [packageManager]
    runs-on: ubuntu-latest
    steps:
      - name: 🛠️ Prepare pnpm workspace
        uses: dyne/pnpm@main
        with:
          node-version: 20
          pnpm-version: ${{ needs.packageManager.outputs.version }}
      - name: 🧪 Run tests
        run: |
          pnpm test

  semantic-release:
    name: 🤖 Semantic release
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    needs: [packageManager, test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 🛠️ Prepare pnpm workspace
        uses: dyne/pnpm@main
        with:
          node-version: 20
          pnpm-version: ${{ needs.packageManager.outputs.version }}
      - run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_docker_image:
    name: 🐳 Publish Docker image
    needs: semantic-release
    if: github.ref == 'refs/heads/main'
    uses: ForkbombEu/workflows/.github/workflows/publish-ghcr.yml@main
    secrets: inherit
